
POST http://localhost:8080/chat
Content-Type: application/json

{
    "agent_name": "WEATHER",
    "message": "What is the weather today at 30041",
    "session_id": "123456"
}

###

POST http://localhost:8080/chat
Content-Type: application/json

{
    "agent_name": "WEATHER",
    "message": "What is the weather today",
    "session_id": "123456"
}

### FINANCE AGENT REQUESTS

POST http://localhost:8080/chat
Content-Type: application/json

{
    "agent_name": "FINANCE",
    "message": "Get me the customer details for CUST001",
    "session_id": "123456"
}

###
POST http://localhost:8080/chat
Content-Type: application/json

{
    "agent_name": "FINANCE",
    "message": "I think I want to contact this customer. Give me his phone",
    "session_id": "123456"
}

###


POST http://localhost:8080/chat
Content-Type: application/json

{
    "agent_name": "FINANCE",
    "message": "Get me the invoices for CUST003",
    "session_id": "123456"
}

###
POST http://localhost:8080/chat
Content-Type: application/json

{
    "agent_name": "FINANCE",
    "message": "Get me the invoices for CUST001",
    "session_id": "123456"
}

###
POST http://localhost:8080/chat
Content-Type: application/json

{
    "agent_name": "FINANCE",
    "message": "Can you please send text message to the customer",
    "session_id": "123456"
}